WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e24b98d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e0e7f3d47ce57b10541be1d734b623c6/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e24c7eb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e0e7f3d47ce57b10541be1d734b623c6/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e24c4490>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e0e7f3d47ce57b10541be1d734b623c6/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e110ec50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/655516707942b98e0e6a824f26f5b896/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e110df60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/655516707942b98e0e6a824f26f5b896/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e110dd20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/655516707942b98e0e6a824f26f5b896/window